// Seed script - populates the database with a curated set of classic films.
// Run with: bun run prisma/seed.ts

import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

interface SeedMovie {
  tmdbId?: number;
  imdbId?: string;
  title: string;
  originalTitle?: string;
  poster?: string;
  backdrop?: string;
  releaseDate?: string;
  year?: number;
  genres: string[];
  runtime?: number;
  country?: string;
  language?: string;
  director?: string;
  writers?: string[];
  cast?: string[];
  overview?: string;
  imdbRating?: number;
  tmdbRating?: number;
  trailer?: string;
  gallery?: string[];
  status?: "watched" | "want" | "watching" | "dropped";
  favorite?: boolean;
  rewatchCount?: number;
  personalRating?: number;
  watchDate?: string;
  notes?: string;
  lifetimeRank?: number;
  tags?: string[];
}

const movies: SeedMovie[] = [
  {
    tmdbId: 263,
    imdbId: "tt0052358",
    title: "Vertigo",
    originalTitle: "Vertigo",
    poster: "/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    backdrop: "/rXuXcQM2k2DDdth5K_FFv1LEpZG.jpg",
    releaseDate: "1958-05-09",
    year: 1958,
    genres: ["Mystery", "Romance", "Thriller"],
    runtime: 128,
    country: "United States of America",
    language: "English",
    director: "Alfred Hitchcock",
    writers: ["Alec Coppel", "Samuel A. Taylor"],
    cast: ["James Stewart", "Kim Novak", "Barbara Bel Geddes"],
    overview:
      "A retired San Francisco detective suffering from acrophobia investigates the strange activities of an old friend's wife, all the while becoming dangerously obsessed with her.",
    imdbRating: 8.3,
    tmdbRating: 8.2,
    trailer: "https://www.youtube.com/watch?v=Z5j9KpQNFjo",
    gallery: ["/rXuXcQM2k2DDdth5K_FFv1LEpZG.jpg", "/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 3,
    personalRating: 10,
    watchDate: "2024-09-15",
    notes: "The ultimate film about obsession. Herrmann's score is transcendent.",
    lifetimeRank: 2,
    tags: ["Masterpiece", "Mind-blowing", "Classic"],
  },
  {
    tmdbId: 346,
    imdbId: "tt0047478",
    title: "Seven Samurai",
    originalTitle: "七人の侍",
    poster: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
    backdrop: "/t4tmRhCVNhI2rT0B2G6dt6uI0EQ.jpg",
    releaseDate: "1954-04-26",
    year: 1954,
    genres: ["Action", "Adventure", "Drama"],
    runtime: 207,
    country: "Japan",
    language: "Japanese",
    director: "Akira Kurosawa",
    writers: ["Akira Kurosawa", "Shinobu Hashimoto", "Hideo Oguni"],
    cast: ["Toshiro Mifune", "Takashi Shimura", "Keiko Tsushima"],
    overview:
      "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves.",
    imdbRating: 8.6,
    tmdbRating: 8.5,
    trailer: "https://www.youtube.com/watch?v=wJG3mKV2-Xg",
    gallery: ["/t4tmRhCVNhI2rT0B2G6dt6uI0EQ.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 2,
    personalRating: 10,
    watchDate: "2024-11-02",
    notes: "The blueprint for the ensemble action film. Every character is unforgettable.",
    lifetimeRank: 5,
    tags: ["Masterpiece", "Classic"],
  },
  {
    tmdbId: 238,
    imdbId: "tt0068646",
    title: "The Godfather",
    originalTitle: "The Godfather",
    poster: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    releaseDate: "1972-03-14",
    year: 1972,
    genres: ["Drama", "Crime"],
    runtime: 175,
    country: "United States of America",
    language: "English",
    director: "Francis Ford Coppola",
    writers: ["Mario Puzo", "Francis Ford Coppola"],
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall"],
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    imdbRating: 9.2,
    tmdbRating: 8.7,
    trailer: "https://www.youtube.com/watch?v=sY1S34973zA",
    gallery: ["/tmU7GeKVybMWFButWEGl2M4GeiP.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 4,
    personalRating: 10,
    watchDate: "2024-06-20",
    notes: "Perfection. The opening sequence alone is a masterclass in filmmaking.",
    lifetimeRank: 1,
    tags: ["Masterpiece", "Classic", "Comfort Movie"],
  },
  {
    tmdbId: 694,
    imdbId: "tt0081505",
    title: "The Shining",
    originalTitle: "The Shining",
    poster: "/b6ko0IKC8MdYBBPkkA1aBPLe2yz.jpg",
    backdrop: "/uIp1bKxBKL08rUWx2dpsxnnUWPa.jpg",
    releaseDate: "1980-05-23",
    year: 1980,
    genres: ["Horror", "Drama", "Mystery"],
    runtime: 144,
    country: "United Kingdom",
    language: "English",
    director: "Stanley Kubrick",
    writers: ["Stanley Kubrick", "Diane Johnson"],
    cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd"],
    overview:
      "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, his wife and son are isolated for the winter. A psychic premonition and a sinister presence drive the father into madness, while his psychic son sees horrific forebodings from both past and future.",
    imdbRating: 8.4,
    tmdbRating: 8.2,
    trailer: "https://www.youtube.com/watch?v=S014oGnHiZg",
    gallery: ["/uIp1bKxBKL08rUWx2dpsxnnUWPa.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 2,
    personalRating: 9.5,
    watchDate: "2024-10-31",
    notes: "Kubrick turns a King novel into pure existential dread. The steadicam work is revolutionary.",
    lifetimeRank: 8,
    tags: ["Masterpiece", "Mind-blowing", "Slow Burn"],
  },
  {
    tmdbId: 769,
    imdbId: "tt0099685",
    title: "GoodFellas",
    originalTitle: "GoodFellas",
    poster: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    backdrop: "/sw7mordbZxgITU877yTpZCud90M.jpg",
    releaseDate: "1990-09-12",
    year: 1990,
    genres: ["Drama", "Crime"],
    runtime: 145,
    country: "United States of America",
    language: "English",
    director: "Martin Scorsese",
    writers: ["Nicholas Pileggi", "Martin Scorsese"],
    cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci", "Lorraine Bracco"],
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    imdbRating: 8.7,
    tmdbRating: 8.5,
    trailer: "https://www.youtube.com/watch?v=2ilzidi_HJQ",
    gallery: ["/sw7mordbZxgITU877yTpZCud90M.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 5,
    personalRating: 9.5,
    watchDate: "2024-07-18",
    notes: "The Copacabana tracking shot. Enough said.",
    lifetimeRank: 7,
    tags: ["Masterpiece", "Classic"],
  },
  {
    tmdbId: 680,
    imdbId: "tt0110912",
    title: "Pulp Fiction",
    originalTitle: "Pulp Fiction",
    poster: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    releaseDate: "1994-09-10",
    year: 1994,
    genres: ["Thriller", "Crime"],
    runtime: 154,
    country: "United States of America",
    language: "English",
    director: "Quentin Tarantino",
    writers: ["Quentin Tarantino", "Roger Avary"],
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    imdbRating: 8.9,
    tmdbRating: 8.5,
    trailer: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
    gallery: ["/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 6,
    personalRating: 9,
    watchDate: "2024-08-05",
    notes: "Rewatchable forever. The dialogue is pure music.",
    lifetimeRank: 12,
    tags: ["Masterpiece", "Mind-blowing", "Classic"],
  },
  {
    tmdbId: 496243,
    imdbId: "tt6751668",
    title: "Parasite",
    originalTitle: "기생충",
    poster: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    releaseDate: "2019-05-30",
    year: 2019,
    genres: ["Comedy", "Drama", "Thriller"],
    runtime: 132,
    country: "Korea, Republic of",
    language: "Korean",
    director: "Bong Joon-ho",
    writers: ["Bong Joon-ho", "Han Jin-won"],
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    imdbRating: 8.5,
    tmdbRating: 8.5,
    trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    gallery: ["/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 2,
    personalRating: 9.5,
    watchDate: "2025-01-12",
    notes: "A tonal high-wire act that never puts a foot wrong.",
    lifetimeRank: 10,
    tags: ["Masterpiece", "Mind-blowing"],
  },
  {
    tmdbId: 69604,
    imdbId: "tt1832382",
    title: "A Separation",
    originalTitle: "جدایی نادر از سیمین",
    poster: "/lwHSloXs7yWpPmBqXK6zo8xYed5.jpg",
    backdrop: "/dCmm7DZSEhMcM7VOEFkRcDKxKb0.jpg",
    releaseDate: "2011-03-16",
    year: 2011,
    genres: ["Drama", "Thriller"],
    runtime: 123,
    country: "Iran",
    language: "Persian",
    director: "Asghar Farhadi",
    writers: ["Asghar Farhadi"],
    cast: ["Peyman Moaadi", "Leila Hatami", "Sareh Bayat", "Shahab Hosseini"],
    overview:
      "When his wife leaves him, an unemployed accordionist is forced to hire a caregiver for his elderly father, leading to a complex web of moral dilemmas and conflict.",
    imdbRating: 8.3,
    tmdbRating: 8.1,
    trailer: "https://www.youtube.com/watch?v=59rOiV2CQ_M",
    gallery: ["/dCmm7DZSEhMcM7VOEFkRDKxKb0.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 2,
    personalRating: 9,
    watchDate: "2025-02-20",
    notes: "No easy answers. Farhadi writes human conflict like no one else.",
    lifetimeRank: 15,
    tags: ["Masterpiece", "Slow Burn"],
  },
  {
    tmdbId: 1124,
    imdbId: "tt0211915",
    title: "Amélie",
    originalTitle: "Le Fabuleux Destin d'Amélie Poulain",
    poster: "/f0uorE7K7ggHfr8r7pUjOITBKHN.jpg",
    backdrop: "/jB0VS0mvjqYDbtHwlORyzf0cWOe.jpg",
    releaseDate: "2001-04-25",
    year: 2001,
    genres: ["Comedy", "Romance"],
    runtime: 122,
    country: "France",
    language: "French",
    director: "Jean-Pierre Jeunet",
    writers: ["Jean-Pierre Jeunet", "Guillaume Laurant"],
    cast: ["Audrey Tautou", "Mathieu Kassovitz", "Rufus"],
    overview:
      "A shy waitress, Amélie, uses her imagination and small acts of kindness to bring joy to those around her, while struggling with her own isolation and a blossoming romance.",
    imdbRating: 8.3,
    tmdbRating: 8.0,
    trailer: "https://www.youtube.com/watch?v=HUECWi5pX7o",
    gallery: ["/jB0VS0mvjqYDbtHwlORyzf0cWOe.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 4,
    personalRating: 9,
    watchDate: "2024-12-08",
    notes: "A warm hug of a film. Tiersen's soundtrack is forever tied to Montmartre.",
    lifetimeRank: 18,
    tags: ["Comfort Movie", "Classic", "Hidden Gem"],
  },
  {
    tmdbId: 62,
    imdbId: "tt0062622",
    title: "2001: A Space Odyssey",
    originalTitle: "2001: A Space Odyssey",
    poster: "/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg",
    backdrop: "/oXUWEc5i3wYyFnL1Ycu8ppxxPvs.jpg",
    releaseDate: "1968-04-10",
    year: 1968,
    genres: ["Science Fiction", "Adventure", "Mystery"],
    runtime: 149,
    country: "United Kingdom",
    language: "English",
    director: "Stanley Kubrick",
    writers: ["Stanley Kubrick", "Arthur C. Clarke"],
    cast: ["Keir Dullea", "Gary Lockwood", "William Sylvester"],
    overview:
      "Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000, the world's most advanced supercomputer.",
    imdbRating: 8.3,
    tmdbRating: 8.1,
    trailer: "https://www.youtube.com/watch?v=oR_e9y-bka0",
    gallery: ["/oXUWEc5i3wYyFnL1Ycu8ppxxPvs.jpg"],
    status: "watched",
    favorite: false,
    rewatchCount: 2,
    personalRating: 9,
    watchDate: "2025-03-01",
    notes: "The monolith. The Strauss waltz. Pure cinema as contemplation.",
    lifetimeRank: 20,
    tags: ["Masterpiece", "Slow Burn", "Classic"],
  },
  {
    tmdbId: 539,
    imdbId: "tt0054215",
    title: "Psycho",
    originalTitle: "Psycho",
    poster: "/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",
    backdrop: "/qaTlUZH8ig0AOiPIfVbYjaY4lwo.jpg",
    releaseDate: "1960-06-22",
    year: 1960,
    genres: ["Horror", "Mystery", "Thriller"],
    runtime: 109,
    country: "United States of America",
    language: "English",
    director: "Alfred Hitchcock",
    writers: ["Joseph Stefano", "Robert Bloch"],
    cast: ["Anthony Perkins", "Vera Miles", "Janet Leigh"],
    overview:
      "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother.",
    imdbRating: 8.5,
    tmdbRating: 8.4,
    trailer: "https://www.youtube.com/watch?v=Ps8HO2WXQKU",
    gallery: ["/qaTlUZH8ig0AOiPIfVbYjaY4lwo.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 3,
    personalRating: 9.5,
    watchDate: "2024-10-13",
    notes: "The shower scene. Hitchcock at his most playful and most cruel.",
    lifetimeRank: 9,
    tags: ["Masterpiece", "Classic", "Mind-blowing"],
  },
  {
    tmdbId: 36,
    imdbId: "tt0047296",
    title: "Rear Window",
    originalTitle: "Rear Window",
    poster: "/qitnZcLP7C9DLRuPpmvZ7GiEjJN.jpg",
    backdrop: "/rThqKyU8t5DOkII7Ztqn4Um0bH.jpg",
    releaseDate: "1954-08-01",
    year: 1954,
    genres: ["Mystery", "Thriller", "Drama"],
    runtime: 112,
    country: "United States of America",
    language: "English",
    director: "Alfred Hitchcock",
    writers: ["John Michael Hayes", "Cornell Woolrich"],
    cast: ["James Stewart", "Grace Kelly", "Wendell Corey", "Thelma Ritter"],
    overview:
      "A wheelchair-bound photographer spies on his neighbours from his apartment window and becomes convinced one of them has committed murder, despite his sceptical girlfriend's disbelief.",
    imdbRating: 8.5,
    tmdbRating: 8.3,
    trailer: "https://www.youtube.com/watch?v=5kIe6UZHSX4",
    gallery: ["/rThqKyU8t5DOkII7ZHSX4Um0bH.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 3,
    personalRating: 9.5,
    watchDate: "2024-09-28",
    notes: "The purest expression of cinema as voyeurism.",
    lifetimeRank: 11,
    tags: ["Masterpiece", "Classic", "Comfort Movie"],
  },
  {
    tmdbId: 637,
    imdbId: "tt0086250",
    title: "Once Upon a Time in America",
    originalTitle: "Once Upon a Time in America",
    poster: "/dQqGzcQ5sM6CZQjwGmPp7eFiezQ.jpg",
    backdrop: "/gJIR7Q4VbHbR1x8fQ7iGj7tQ8qZ.jpg",
    releaseDate: "1984-05-23",
    year: 1984,
    genres: ["Drama", "Crime"],
    runtime: 229,
    country: "United States of America",
    language: "English",
    director: "Sergio Leone",
    writers: ["Sergio Leone", "Leonardo Benvenuti", "Enrico Medioli"],
    cast: ["Robert De Niro", "James Woods", "Elizabeth McGovern"],
    overview:
      "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.",
    imdbRating: 8.3,
    tmdbRating: 8.2,
    trailer: "https://www.youtube.com/watch?v=5iY9bXJUZQw",
    gallery: [],
    status: "want",
    favorite: false,
    rewatchCount: 0,
    personalRating: null,
    watchDate: null,
    notes: null,
    lifetimeRank: null,
    tags: ["Slow Burn", "Classic"],
  },
  {
    tmdbId: 11216,
    imdbId: "tt0042192",
    title: "Bicycle Thieves",
    originalTitle: "Ladri di biciclette",
    poster: "/4yFG6cSPaCaPhyJ1vtGOtMD1lgh.jpg",
    backdrop: "/8mUlH98ajYQjhcfQjzMywg5r5LT.jpg",
    releaseDate: "1948-11-24",
    year: 1948,
    genres: ["Drama"],
    runtime: 89,
    country: "Italy",
    language: "Italian",
    director: "Vittorio De Sica",
    writers: ["Cesare Zavattini", "Luigi Bartolini"],
    cast: ["Lamberto Maggiorani", "Enzo Staiola", "Lianella Carell"],
    overview:
      "Antonio, an unemployed man in the depressed post-WWII economy of Italy, finally gets a good job hanging posters, which requires a bicycle. But his bicycle is stolen, and he and his son set out to find it.",
    imdbRating: 8.3,
    tmdbRating: 8.1,
    trailer: "https://www.youtube.com/watch?v=H3I1I3a9bXg",
    gallery: ["/8mUlH98ajYQjhcfQjzMywg5r5LT.jpg"],
    status: "watched",
    favorite: false,
    rewatchCount: 1,
    personalRating: 9,
    watchDate: "2025-02-08",
    notes: "Neorealism at its most devastating. The ending stays with you.",
    lifetimeRank: 25,
    tags: ["Masterpiece", "Slow Burn"],
  },
  {
    tmdbId: 9440,
    imdbId: "tt0457439",
    title: "Pan's Labyrinth",
    originalTitle: "El laberinto del fauno",
    poster: "/4kJoFbBLuoYczAUJZjPpEYNxfgU.jpg",
    backdrop: "/rRdGOw8LrJaKtM4hVjd6LA0uDmO.jpg",
    releaseDate: "2006-10-11",
    year: 2006,
    genres: ["Fantasy", "Drama", "War"],
    runtime: 118,
    country: "Spain",
    language: "Spanish",
    director: "Guillermo del Toro",
    writers: ["Guillermo del Toro"],
    cast: ["Ivana Baquero", "Sergi López", "Maribel Verdú", "Doug Jones"],
    overview:
      "In the falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
    imdbRating: 8.2,
    tmdbRating: 8.0,
    trailer: "https://www.youtube.com/watch?v=EqYiSlkvRua",
    gallery: ["/rRdGOw8LrJaKtM4hVjd6LA0uDmO.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 2,
    personalRating: 9,
    watchDate: "2024-11-20",
    notes: "A dark fairy tale for adults. The Pale Man haunts my dreams.",
    lifetimeRank: 22,
    tags: ["Masterpiece", "Mind-blowing"],
  },
  {
    tmdbId: 670,
    imdbId: "tt0076759",
    title: "Star Wars",
    originalTitle: "Star Wars",
    poster: "/6FfRtQ8XyKpbI5W2PIy7IeqmFhD.jpg",
    backdrop: "/zqkmTXzjkAgXmEWLRsY4UpTWCrI.jpg",
    releaseDate: "1977-05-25",
    year: 1977,
    genres: ["Science Fiction", "Adventure", "Action"],
    runtime: 121,
    country: "United States of America",
    language: "English",
    director: "George Lucas",
    writers: ["George Lucas"],
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Alec Guinness"],
    overview:
      "Princess Leia is captured and held hostage by the evil Imperial forces. Luke Skywalker and Han Solo work together to rescue her and bring peace to the galaxy.",
    imdbRating: 8.6,
    tmdbRating: 8.2,
    trailer: "https://www.youtube.com/watch?v=vZ734NWnAHA",
    gallery: ["/zqkmTXzjkAgXmEWLRsY4UpTWCrI.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 8,
    personalRating: 9,
    watchDate: "2024-05-04",
    notes: "The one that started it all. Pure mythic storytelling.",
    lifetimeRank: 16,
    tags: ["Classic", "Comfort Movie"],
  },
  {
    tmdbId: 13,
    imdbId: "tt0080684",
    title: "Forrest Gump",
    originalTitle: "Forrest Gump",
    poster: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    backdrop: "/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
    releaseDate: "1994-06-23",
    year: 1994,
    genres: ["Comedy", "Drama", "Romance"],
    runtime: 142,
    country: "United States of America",
    language: "English",
    director: "Robert Zemeckis",
    writers: ["Eric Roth", "Winston Groom"],
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events while longing for his childhood sweetheart.",
    imdbRating: 8.8,
    tmdbRating: 8.5,
    trailer: "https://www.youtube.com/watch?v=bLvqoHBptjg",
    gallery: ["/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg"],
    status: "watched",
    favorite: false,
    rewatchCount: 4,
    personalRating: 8.5,
    watchDate: "2024-04-12",
    notes: "Life is like a box of chocolates. Comfort viewing at its finest.",
    lifetimeRank: 28,
    tags: ["Comfort Movie", "Classic"],
  },
  {
    tmdbId: 27205,
    imdbId: "tt1375666",
    title: "Inception",
    originalTitle: "Inception",
    poster: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdrop: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    releaseDate: "2010-07-15",
    year: 2010,
    genres: ["Science Fiction", "Action", "Adventure"],
    runtime: 148,
    country: "United States of America",
    language: "English",
    director: "Christopher Nolan",
    writers: ["Christopher Nolan"],
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    overview:
      "A skilled thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    imdbRating: 8.8,
    tmdbRating: 8.4,
    trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    gallery: ["/s3TBrRGB1iav7gFOCNx3H31MoES.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 5,
    personalRating: 9,
    watchDate: "2024-08-22",
    notes: "A heist movie inside a dream inside a dream. Nolan's ambition is staggering.",
    lifetimeRank: 19,
    tags: ["Mind-blowing", "Classic"],
  },
  {
    tmdbId: 155,
    imdbId: "tt0114369",
    title: "Se7en",
    originalTitle: "Se7en",
    poster: "/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    backdrop: "/ba4CpvnaxvAgff2jHiaqJrVpZJ5.jpg",
    releaseDate: "1995-09-22",
    year: 1995,
    genres: ["Crime", "Mystery", "Thriller"],
    runtime: 127,
    country: "United States of America",
    language: "English",
    director: "David Fincher",
    writers: ["Andrew Kevin Walker"],
    cast: ["Brad Pitt", "Morgan Freeman", "Kevin Spacey", "Gwyneth Paltrow"],
    overview:
      "Two homicide detectives track a serial killer who justifies his crimes as absolution for the world's ignorance of the Seven Deadly Sins.",
    imdbRating: 8.6,
    tmdbRating: 8.4,
    trailer: "https://www.youtube.com/watch?v=znmZoVkCjpI",
    gallery: ["/ba4CpvnaxvAgff2jHiaqJrVpZJ5.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 3,
    personalRating: 9.5,
    watchDate: "2024-10-20",
    notes: "What's in the box?! Fincher crafts dread like few others.",
    lifetimeRank: 14,
    tags: ["Masterpiece", "Mind-blowing", "Slow Burn"],
  },
  {
    tmdbId: 680,
    imdbId: "tt0364569",
    title: "Oldboy",
    originalTitle: "올드보이",
    poster: "/pWDtjs568ZfOTMbURQBYuT4Qeja.jpg",
    backdrop: "/8GVcMqU5GpQLyJhqfzp6AyzNprv.jpg",
    releaseDate: "2003-11-21",
    year: 2003,
    genres: ["Action", "Mystery", "Thriller"],
    runtime: 120,
    country: "Korea, Republic of",
    language: "Korean",
    director: "Park Chan-wook",
    writers: ["Park Chan-wook", "Garin Tsuchiya", "Nobuaki Minegishi"],
    cast: ["Choi Min-sik", "Yoo Ji-tae", "Kang Hye-jung"],
    overview:
      "After being kidnapped and imprisoned for fifteen years without knowing why, Oh Dae-su is released and given five days to discover his captor.",
    imdbRating: 8.3,
    tmdbRating: 8.0,
    trailer: "https://www.youtube.com/watch?v=V5JsfYgYSk0",
    gallery: ["/8GVcMqU5GpQLyJhNprv.jpg"],
    status: "want",
    favorite: false,
    rewatchCount: 0,
    personalRating: null,
    watchDate: null,
    notes: null,
    lifetimeRank: null,
    tags: ["Mind-blowing"],
  },
  {
    tmdbId: 24428,
    imdbId: "tt0848228",
    title: "The Avengers",
    originalTitle: "The Avengers",
    poster: "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    backdrop: "/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
    releaseDate: "2012-05-04",
    year: 2012,
    genres: ["Science Fiction", "Action", "Adventure"],
    runtime: 143,
    country: "United States of America",
    language: "English",
    director: "Joss Whedon",
    writers: ["Joss Whedon"],
    cast: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson", "Chris Hemsworth"],
    overview:
      "When an unexpected enemy emerges and threatens global safety, Nick Fury finds himself in need of a team to pull the world back from the brink of disaster.",
    imdbRating: 8.0,
    tmdbRating: 7.7,
    trailer: "https://www.youtube.com/watch?v=eOrNdBqGMyc",
    gallery: ["/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg"],
    status: "watched",
    favorite: false,
    rewatchCount: 2,
    personalRating: 7.5,
    watchDate: "2024-03-15",
    notes: "Fun blockbuster. The first time the team-up really worked.",
    lifetimeRank: null,
    tags: ["Comfort Movie"],
  },
  {
    tmdbId: 129,
    imdbId: "tt0118799",
    title: "Life Is Beautiful",
    originalTitle: "La vita è bella",
    poster: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    backdrop: "/bORe0eI72D874TMawOOFvqWS6Xb.jpg",
    releaseDate: "1997-12-20",
    year: 1997,
    genres: ["Comedy", "Drama", "Romance"],
    runtime: 116,
    country: "Italy",
    language: "Italian",
    director: "Roberto Benigni",
    writers: ["Roberto Benigni", "Vincenzo Cerami"],
    cast: ["Roberto Benigni", "Nicoletta Braschi", "Giorgio Cantarini"],
    overview:
      "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale world with his wife and son, until their lives are changed by World War II.",
    imdbRating: 8.6,
    tmdbRating: 8.3,
    trailer: "https://www.youtube.com/watch?v=pAy-K7B1uYg",
    gallery: ["/bORe0eI72D874TMawOOFvqWS6Xb.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 2,
    personalRating: 9,
    watchDate: "2025-01-25",
    notes: "Heartbreaking and hilarious in equal measure.",
    lifetimeRank: 21,
    tags: ["Masterpiece", "Comfort Movie"],
  },
  {
    tmdbId: 372058,
    imdbId: "tt6105098",
    title: "Your Name",
    originalTitle: "君の名は。",
    poster: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    backdrop: "/mMtUybQ6hL24FXo0F3Z4jxKGZjr.jpg",
    releaseDate: "2016-08-26",
    year: 2016,
    genres: ["Romance", "Animation", "Drama"],
    runtime: 106,
    country: "Japan",
    language: "Japanese",
    director: "Makoto Shinkai",
    writers: ["Makoto Shinkai"],
    cast: ["Ryunosuke Kamiki", "Mone Kamishiraishi", "Nobunaga Shimazaki"],
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki's body, and he in hers.",
    imdbRating: 8.4,
    tmdbRating: 8.5,
    trailer: "https://www.youtube.com/watch?v=xU47nhruN-Q",
    gallery: ["/mMtUybQ6hL24FXo0F3Z4jxKGZjr.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 3,
    personalRating: 9,
    watchDate: "2024-12-15",
    notes: "Breathtaking animation and a story that sneaks up on you.",
    lifetimeRank: 24,
    tags: ["Mind-blowing", "Comfort Movie"],
  },
  {
    tmdbId: 280,
    imdbId: "tt0137523",
    title: "Fight Club",
    originalTitle: "Fight Club",
    poster: "/pB8BM7pdSp6B6Ih7QZ4DrQIVP28.jpg",
    backdrop: "/87hTDiay2N2qWyX4Ds7yXi2h3IY.jpg",
    releaseDate: "1999-10-15",
    year: 1999,
    genres: ["Drama", "Thriller"],
    runtime: 139,
    country: "United States of America",
    language: "English",
    director: "David Fincher",
    writers: ["Jim Uhls", "Chuck Palahniuk"],
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    overview:
      "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground 'fight clubs' forming in every town.",
    imdbRating: 8.8,
    tmdbRating: 8.4,
    trailer: "https://www.youtube.com/watch?v=qtRKdVHc-cE",
    gallery: ["/87hTDiay2N2qWyX4Ds7yXi2h3IY.jpg"],
    status: "watched",
    favorite: false,
    rewatchCount: 2,
    personalRating: 8.5,
    watchDate: "2024-05-18",
    notes: "The first rule... you know the rest. Still packs a punch.",
    lifetimeRank: 30,
    tags: ["Mind-blowing", "Classic"],
  },
  {
    tmdbId: 1892,
    imdbId: "tt0113277",
    title: "Heat",
    originalTitle: "Heat",
    poster: "/zMyfPUHNlHErhbU0kuhfuXtSmwv.jpg",
    backdrop: "/g41t1Ie6mZ50UIvkUuYa6PMqQYg.jpg",
    releaseDate: "1995-12-15",
    year: 1995,
    genres: ["Action", "Crime", "Drama", "Thriller"],
    runtime: 170,
    country: "United States of America",
    language: "English",
    director: "Michael Mann",
    writers: ["Michael Mann"],
    cast: ["Al Pacino", "Robert De Niro", "Val Kilmer", "Jon Voight"],
    overview:
      "Hunter becomes the hunted as a crew of highly skilled armed robbers is pursued by an obsessed LAPD detective. The lines blur between cop and criminal.",
    imdbRating: 8.3,
    tmdbRating: 8.0,
    trailer: "https://www.youtube.com/watch?v=SrUgVSPiCmM",
    gallery: ["/g41t1Ie6mZ50UIvkUyYa6PMqQYg.jpg"],
    status: "want",
    favorite: false,
    rewatchCount: 0,
    personalRating: null,
    watchDate: null,
    notes: null,
    lifetimeRank: null,
    tags: ["Slow Burn", "Classic"],
  },
  {
    tmdbId: 76341,
    imdbId: "tt2911666",
    title: "Mad Max: Fury Road",
    originalTitle: "Mad Max: Fury Road",
    poster: "/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    backdrop: "/gqrnQA6Xppdl8vIb2eJc58VC1tW.jpg",
    releaseDate: "2015-05-15",
    year: 2015,
    genres: ["Action", "Adventure", "Science Fiction"],
    runtime: 120,
    country: "Australia",
    language: "English",
    director: "George Miller",
    writers: ["George Miller", "Brendan McCarthy", "Nick Lathouris"],
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
    overview:
      "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and almost everyone is crazed fighting for the necessities of life.",
    imdbRating: 8.1,
    tmdbRating: 7.6,
    trailer: "https://www.youtube.com/watch?v=hEJnMQG9ev8",
    gallery: ["/gqrnQA6Xppdl8vIb2eJc58VC1tW.jpg"],
    status: "watched",
    favorite: true,
    rewatchCount: 2,
    personalRating: 9,
    watchDate: "2025-03-10",
    notes: "Two hours of pure kinetic poetry. Witness me.",
    lifetimeRank: 23,
    tags: ["Mind-blowing", "Classic"],
  },
];

async function main() {
  console.log("Seeding database...");

  // Clear existing
  await db.movie.deleteMany({});
  await db.collection.deleteMany({});
  await db.personalList.deleteMany({});

  for (const m of movies) {
    await db.movie.create({
      data: {
        tmdbId: m.tmdbId ?? null,
        imdbId: m.imdbId ?? null,
        title: m.title,
        originalTitle: m.originalTitle ?? null,
        poster: m.poster ?? null,
        backdrop: m.backdrop ?? null,
        releaseDate: m.releaseDate ?? null,
        year: m.year ?? null,
        genres: JSON.stringify(m.genres),
        runtime: m.runtime ?? null,
        country: m.country ?? null,
        language: m.language ?? null,
        director: m.director ?? null,
        writers: JSON.stringify(m.writers ?? []),
        cast: JSON.stringify(m.cast ?? []),
        overview: m.overview ?? null,
        imdbRating: m.imdbRating ?? null,
        tmdbRating: m.tmdbRating ?? null,
        trailer: m.trailer ?? null,
        gallery: JSON.stringify(m.gallery ?? []),
        status: m.status ?? "watched",
        favorite: m.favorite ?? false,
        rewatchCount: m.rewatchCount ?? 0,
        personalRating: m.personalRating ?? null,
        watchDate: m.watchDate ?? null,
        notes: m.notes ?? null,
        lifetimeRank: m.lifetimeRank ?? null,
        tags: JSON.stringify(m.tags ?? []),
      },
    });
  }

  // Sample collections
  await db.collection.create({
    data: {
      name: "Best Hitchcock Movies",
      description: "The master of suspense at his finest.",
      movieIds: JSON.stringify([]),
    },
  });

  await db.collection.create({
    data: {
      name: "Movies to Rewatch",
      description: "Films that deserve another viewing.",
      movieIds: JSON.stringify([]),
    },
  });

  // Sample personal list
  await db.personalList.create({
    data: {
      name: "My Top 10 Crime Films",
      description: "The cream of the criminal crop.",
      items: JSON.stringify([]),
    },
  });

  console.log(`Seeded ${movies.length} movies, 2 collections, 1 list.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
